# Generated by Django 5.2 on 2025-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "issue_category",
                    models.CharField(
                        choices=[
                            ("billing", "Billing Issue"),
                            ("tech", "Technical Support"),
                            ("general", "General Inquiry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
